export const SAGA_INITIALIZE_TABLE = "TABLE/SAGA_INITIALIZE_TABLE";
export const SET_TOTAL_LENGTH = "TABLE/SET_TOTAL_LENGTH";
export const SET_CURRENT_PAGE = "TABLE/SET_CURRENT_PAGE";
export const SET_TABLE_DATA = "TABLE/SET_TABLE_DATA";
export const SAGA_SET_TABLE_DATA = "TABLE/SAGA_SET_TABLE_DATA";
export const ITEM_PER_PAGE = 10;
